<?php
require_once __DIR__.'/../bd/database.php';require_once __DIR__.'/../bd/desktop_session.php';
if(!function_exists('desktop_session_presence_leave')){function desktop_session_presence_leave(mysqli $db):void{return;}}
if(!function_exists('desktop_online_expression')){function desktop_online_expression(string $userAlias='u'):string{$alias=preg_replace('/[^a-z0-9_]/i','',$userAlias)?:'u';return "$alias.last_seen>=DATE_SUB(NOW(),INTERVAL 20 SECOND)";}}
desktop_cors();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');header('X-Kitchat-Community-Build: 1.4.85-compat');mysqli_report(MYSQLI_REPORT_OFF);@mysqli_set_charset($link,'utf8mb4');
$uid=isset($_COOKIE['id'])?(int)$_COOKIE['id']:desktop_session_user($link); if($uid<=0){http_response_code(401);echo json_encode(['ok'=>false]);exit;}
function out($v,$c=200){http_response_code($c);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
set_exception_handler(function(Throwable $e){error_log('community api: '.$e->getMessage());out(['ok'=>false,'error'=>'Ошибка сервера сообщества'],500);});
function admin_user($id){global $link;static $cache=[];$id=(int)$id;if($id<=0)return false;if(array_key_exists($id,$cache))return $cache[$id];$r=mysqli_query($link,"SELECT global_role FROM user WHERE id=$id LIMIT 1");$row=$r?mysqli_fetch_assoc($r):null;return $cache[$id]=(($row['global_role']??'user')==='superadmin');}
function community_role_level($role){return ['member'=>10,'moderator'=>20,'admin'=>30,'owner'=>40,'superadmin'=>100][(string)$role]??0;}
function community_server_role($db,$sid,$userId){if(admin_user($userId))return 'superadmin';$sid=(int)$sid;$userId=(int)$userId;$r=mysqli_query($db,"SELECT role FROM community_server_members WHERE server_id=$sid AND user_id=$userId LIMIT 1");$row=$r?mysqli_fetch_assoc($r):null;return (string)($row['role']??'');}
function community_can($db,$sid,$userId,$minimum){return community_role_level(community_server_role($db,$sid,$userId))>=community_role_level($minimum);}
function ensure_column($db,$table,$column,$definition){$safeTable=preg_replace('/[^a-z0-9_]/i','',$table);$safeColumn=preg_replace('/[^a-z0-9_]/i','',$column);$r=mysqli_query($db,"SHOW COLUMNS FROM `$safeTable` LIKE '$safeColumn'");if(!$r||!mysqli_fetch_assoc($r))mysqli_query($db,"ALTER TABLE `$safeTable` ADD COLUMN `$safeColumn` $definition");}
function channel_slug($name){$s=mb_strtolower(trim($name));$s=strtr($s,['а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e','ё'=>'e','ж'=>'zh','з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'h','ц'=>'c','ч'=>'ch','ш'=>'sh','щ'=>'sch','ъ'=>'','ы'=>'y','ь'=>'','э'=>'e','ю'=>'yu','я'=>'ya']);$s=preg_replace('/[^a-z0-9]+/','-',$s);return trim($s,'-')?:'channel';}
function save_server_icon($file,$sid){if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>5*1024*1024)return null;$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'][$mime]??null;if(!$ext||!@getimagesize($file['tmp_name']))return null;$dir=dirname(__DIR__).'/uploads/community';if(!is_dir($dir)&&!@mkdir($dir,0775,true))return null;$name='server-'.$sid.'-'.bin2hex(random_bytes(6)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))return null;return '/uploads/community/'.$name;}
function save_sticker($file,$sid){if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>8*1024*1024)return null;$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'][$mime]??null;if(!$ext||!@getimagesize($file['tmp_name']))return null;$dir=dirname(__DIR__).'/uploads/community/stickers';if(!is_dir($dir)&&!@mkdir($dir,0775,true))return null;$name='sticker-'.$sid.'-'.bin2hex(random_bytes(8)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))return null;return '/uploads/community/stickers/'.$name;}
function save_attachment($file,$sid){if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>25*1024*1024)return null;$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name'])?:'application/octet-stream';$allowed=str_starts_with($mime,'image/')||str_starts_with($mime,'video/')||str_starts_with($mime,'audio/')||str_starts_with($mime,'text/')||in_array($mime,['application/pdf','application/zip','application/x-zip-compressed'],true);if(!$allowed)return null;$original=mb_substr(basename((string)$file['name']),0,120);$ext=strtolower(pathinfo($original,PATHINFO_EXTENSION));$safeName=preg_replace('/[^a-zA-Z0-9._-]+/','-',$original)?:'file'.($ext?'.'.$ext:'');$dir=dirname(__DIR__).'/uploads/community/files/'.$sid;if(!is_dir($dir)&&!@mkdir($dir,0775,true))return null;$stored=bin2hex(random_bytes(10)).($ext?'.'.$ext:'');if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$stored))return null;return ['name'=>$safeName,'path'=>'/uploads/community/files/'.$sid.'/'.$stored,'mime'=>$mime,'size'=>(int)$file['size']];}
function delete_uploaded_path($path){$path=(string)$path;if(!str_starts_with($path,'/uploads/community/'))return;$root=realpath(dirname(__DIR__).'/uploads/community');$file=realpath(dirname(__DIR__).$path);if($root&&$file&&str_starts_with($file,$root.DIRECTORY_SEPARATOR)&&is_file($file))@unlink($file);}
function delete_message_asset($encrypted){try{$plain=chat_decrypt($encrypted);}catch(Throwable $e){return;}if(preg_match('/^\[\[file:([A-Za-z0-9+\/=]+)\]\]$/',$plain,$m)){$file=json_decode(base64_decode($m[1]),true);if(is_array($file)&&!empty($file['path']))delete_uploaded_path($file['path']);}}
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_channels(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(48) NOT NULL UNIQUE,name VARCHAR(60) NOT NULL,topic VARCHAR(180) NOT NULL DEFAULT '',type ENUM('text','voice') NOT NULL DEFAULT 'text',owner_id INT NOT NULL DEFAULT 0,position INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY(type,position)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_servers(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL,icon VARCHAR(255) NULL,banner VARCHAR(32) NOT NULL DEFAULT '#5865f2',description VARCHAR(500) NOT NULL DEFAULT '',owner_id INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY(owner_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_server_members(server_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,role ENUM('owner','member') NOT NULL DEFAULT 'member',joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(server_id,user_id),KEY(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,server_id INT UNSIGNED NOT NULL DEFAULT 0,channel VARCHAR(48) NOT NULL,user_id INT NOT NULL,message MEDIUMBLOB NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_community_channel(channel,id),KEY(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_stickers(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,server_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,name VARCHAR(60) NOT NULL,path VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY(server_id),KEY(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS desktop_profile_about(user_id INT NOT NULL PRIMARY KEY,about VARCHAR(190) NOT NULL DEFAULT '',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_profile_about_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
ensure_column($link,'community_channels','server_id','INT UNSIGNED NOT NULL DEFAULT 0 AFTER `id`');
ensure_column($link,'community_channels','voice_mode',"ENUM('p2p','livekit') NOT NULL DEFAULT 'p2p' AFTER `type`");
ensure_column($link,'community_messages','server_id','INT UNSIGNED NOT NULL DEFAULT 0 AFTER `id`');
ensure_column($link,'community_messages','edited_at','DATETIME NULL DEFAULT NULL AFTER `created_at`');
ensure_column($link,'user','global_role',"ENUM('user','superadmin') NOT NULL DEFAULT 'user'");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_message_reads(server_id INT UNSIGNED NOT NULL,channel VARCHAR(48) NOT NULL,user_id INT NOT NULL,last_message_id BIGINT UNSIGNED NOT NULL DEFAULT 0,read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(server_id,channel,user_id),KEY(last_message_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_voice_presence(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,muted TINYINT(1) NOT NULL DEFAULT 0,joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,heartbeat_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(channel_id,user_id),KEY(heartbeat_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ensure_column($link,'community_voice_presence','deafened','TINYINT(1) NOT NULL DEFAULT 0 AFTER `muted`');
ensure_column($link,'community_voice_presence','speaking','TINYINT(1) NOT NULL DEFAULT 0 AFTER `deafened`');
ensure_column($link,'community_voice_presence','sharing','TINYINT(1) NOT NULL DEFAULT 0 AFTER `speaking`');
ensure_column($link,'community_voice_presence','camera','TINYINT(1) NOT NULL DEFAULT 0 AFTER `sharing`');
// A user may be present in exactly one voice channel. Clean up legacy duplicates
// before installing the database-level guarantee.
mysqli_query($link,"DELETE older FROM community_voice_presence older JOIN community_voice_presence newer ON newer.user_id=older.user_id AND (newer.heartbeat_at>older.heartbeat_at OR (newer.heartbeat_at=older.heartbeat_at AND newer.channel_id>older.channel_id))");
$voiceUserIndex=mysqli_query($link,"SHOW INDEX FROM community_voice_presence WHERE Key_name='unique_voice_user'");
if(!$voiceUserIndex||!mysqli_fetch_assoc($voiceUserIndex))mysqli_query($link,"ALTER TABLE community_voice_presence ADD UNIQUE KEY unique_voice_user(user_id)");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_voice_signals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,channel_id INT UNSIGNED NOT NULL,sender_id INT NOT NULL,receiver_id INT NOT NULL,payload MEDIUMTEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY(receiver_id,channel_id,id),KEY(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$roleColumn=mysqli_query($link,"SHOW COLUMNS FROM community_server_members LIKE 'role'");$roleInfo=$roleColumn?mysqli_fetch_assoc($roleColumn):null;if($roleInfo&&!str_contains((string)$roleInfo['Type'],'moderator'))mysqli_query($link,"ALTER TABLE community_server_members MODIFY role ENUM('owner','admin','moderator','member') NOT NULL DEFAULT 'member'");
mysqli_query($link,"CREATE TABLE IF NOT EXISTS community_server_invites(code CHAR(32) PRIMARY KEY,server_id INT UNSIGNED NOT NULL,created_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NULL,uses INT NOT NULL DEFAULT 0,KEY(server_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
mysqli_query($link,"DELETE FROM community_channels WHERE owner_id=0 AND slug IN ('general','kitchen','ideas','table')");
mysqli_query($link,"DELETE FROM community_voice_presence WHERE heartbeat_at<DATE_SUB(NOW(),INTERVAL 25 SECOND)");mysqli_query($link,"DELETE FROM community_voice_signals WHERE created_at<DATE_SUB(NOW(),INTERVAL 3 MINUTE)");
mysqli_query($link,"UPDATE user SET last_seen=NOW() WHERE id=$uid");
$isSupreme=admin_user($uid);
// «Самый главный» видит все серверы. Членство добавляется автоматически, чтобы
// обычные запросы сообщений, голоса и signaling продолжали работать одинаково.
if($isSupreme)mysqli_query($link,"INSERT IGNORE INTO community_server_members(server_id,user_id,role) SELECT id,$uid,'admin' FROM community_servers");
$action=$_REQUEST['action']??'state';
if($action==='presence_leave'&&$_SERVER['REQUEST_METHOD']==='POST'){desktop_session_presence_leave($link);mysqli_query($link,"DELETE FROM community_voice_presence WHERE user_id=$uid");mysqli_query($link,"DELETE FROM community_voice_signals WHERE sender_id=$uid OR receiver_id=$uid");out(['ok'=>true]);}
if($action==='create_server'&&$_SERVER['REQUEST_METHOD']==='POST'){$name=mb_substr(trim((string)($_POST['name']??'')),0,80);if($name==='')out(['ok'=>false,'error'=>'Введите название сервера'],422);$st=mysqli_prepare($link,"INSERT INTO community_servers(name,owner_id) VALUES(?,?)");mysqli_stmt_bind_param($st,'si',$name,$uid);mysqli_stmt_execute($st);$sid=(int)mysqli_insert_id($link);mysqli_query($link,"INSERT INTO community_server_members(server_id,user_id,role) VALUES($sid,$uid,'owner')");$base=substr(bin2hex(random_bytes(4)),0,7);mysqli_query($link,"INSERT INTO community_channels(server_id,slug,name,topic,type,owner_id,position) VALUES($sid,'main-$base','основной','Главный канал сервера','text',$uid,10),($sid,'voice-$base','Основной','Голосовой канал','voice',$uid,20)");out(['ok'=>true,'server_id'=>$sid]);}
if($action==='update_server'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$name=mb_substr(trim((string)($_POST['name']??'')),0,80);$description=mb_substr(trim((string)($_POST['description']??'')),0,500);$banner=preg_match('/^#[0-9a-f]{6}$/i',(string)($_POST['banner']??''))?$_POST['banner']:'#5865f2';if(!community_can($link,$sid,$uid,'admin'))out(['ok'=>false,'error'=>'Профиль сервера могут менять владелец и администраторы'],403);$st=mysqli_prepare($link,"UPDATE community_servers SET name=?,description=?,banner=? WHERE id=?");mysqli_stmt_bind_param($st,'sssi',$name,$description,$banner,$sid);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='upload_server_icon'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);if(!community_can($link,$sid,$uid,'admin'))out(['ok'=>false,'error'=>'Профиль сервера могут менять владелец и администраторы'],403);$path=save_server_icon($_FILES['icon']??null,$sid);if(!$path)out(['ok'=>false,'error'=>'Выберите JPG, PNG, WEBP или GIF до 5 МБ'],422);$st=mysqli_prepare($link,"UPDATE community_servers SET icon=? WHERE id=?");mysqli_stmt_bind_param($st,'si',$path,$sid);mysqli_stmt_execute($st);out(['ok'=>true,'icon'=>$path]);}
if($action==='delete_server'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$own=mysqli_query($link,"SELECT 1 FROM community_servers WHERE id=$sid AND owner_id=$uid");if((!$own||!mysqli_fetch_row($own))&&!$isSupreme)out(['ok'=>false,'error'=>'Удалить сервер может только владелец'],403);$assets=mysqli_query($link,"SELECT message FROM community_messages WHERE server_id=$sid");while($assets&&$asset=mysqli_fetch_assoc($assets))delete_message_asset($asset['message']);$stickers=mysqli_query($link,"SELECT path FROM community_stickers WHERE server_id=$sid");while($stickers&&$sticker=mysqli_fetch_assoc($stickers))delete_uploaded_path($sticker['path']);mysqli_query($link,"DELETE FROM community_servers WHERE id=$sid");mysqli_query($link,"DELETE FROM community_server_members WHERE server_id=$sid");mysqli_query($link,"DELETE FROM community_channels WHERE server_id=$sid");mysqli_query($link,"DELETE FROM community_messages WHERE server_id=$sid");mysqli_query($link,"DELETE FROM community_stickers WHERE server_id=$sid");mysqli_query($link,"DELETE FROM community_server_invites WHERE server_id=$sid");out(['ok'=>true]);}
if($action==='leave_server'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$r=mysqli_query($link,"SELECT owner_id FROM community_servers WHERE id=$sid");$server=$r?mysqli_fetch_assoc($r):null;if(!$server)out(['ok'=>false,'error'=>'Сервер не найден'],404);if((int)$server['owner_id']===$uid)out(['ok'=>false,'error'=>'Владелец не может выйти из сервера. Передайте владение или удалите сервер.'],422);mysqli_query($link,"DELETE FROM community_voice_presence WHERE user_id=$uid AND channel_id IN(SELECT id FROM community_channels WHERE server_id=$sid)");mysqli_query($link,"DELETE FROM community_server_members WHERE server_id=$sid AND user_id=$uid");out(['ok'=>true]);}
if($action==='kick_member'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$other=(int)($_POST['user_id']??0);$myRole=community_server_role($link,$sid,$uid);$otherRole=community_server_role($link,$sid,$other);if($other<=0||$other===$uid||community_role_level($myRole)<community_role_level('admin')||community_role_level($myRole)<=community_role_level($otherRole))out(['ok'=>false,'error'=>'Нельзя выгнать пользователя с равной или более высокой ролью'],403);mysqli_query($link,"DELETE FROM community_voice_presence WHERE user_id=$other AND channel_id IN(SELECT id FROM community_channels WHERE server_id=$sid)");mysqli_query($link,"DELETE FROM community_server_members WHERE server_id=$sid AND user_id=$other");out(['ok'=>true]);}
if($action==='kick_voice'&&$_SERVER['REQUEST_METHOD']==='POST'){$cid=(int)($_POST['channel_id']??0);$other=(int)($_POST['user_id']??0);$r=mysqli_query($link,"SELECT server_id FROM community_channels WHERE id=$cid AND type='voice'");$channel=$r?mysqli_fetch_assoc($r):null;$sid=(int)($channel['server_id']??0);if(!$sid||$other<=0||$other===$uid||!community_can($link,$sid,$uid,'moderator'))out(['ok'=>false,'error'=>'Отключать от голосового могут модераторы и выше'],403);mysqli_query($link,"DELETE FROM community_voice_presence WHERE channel_id=$cid AND user_id=$other");out(['ok'=>true]);}
if($action==='add_member'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$other=(int)($_POST['user_id']??0);if(!community_can($link,$sid,$uid,'admin'))out(['ok'=>false,'error'=>'Приглашать участников могут владелец и администраторы'],403);$friend=mysqli_query($link,"SELECT 1 FROM friends WHERE status=1 AND ((user_id=$uid AND friend_id=$other)OR(friend_id=$uid AND user_id=$other))");if(!$friend||!mysqli_fetch_row($friend))out(['ok'=>false,'error'=>'Сначала добавьте пользователя в друзья'],403);mysqli_query($link,"INSERT IGNORE INTO community_server_members(server_id,user_id) VALUES($sid,$other)");out(['ok'=>true]);}
if($action==='set_member_role'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$other=(int)($_POST['user_id']??0);$role=(string)($_POST['role']??'member');if(!in_array($role,['admin','moderator','member'],true))out(['ok'=>false],422);$own=mysqli_query($link,"SELECT 1 FROM community_servers WHERE id=$sid AND owner_id=$uid");if((!$own||!mysqli_fetch_row($own))&&!$isSupreme)out(['ok'=>false,'error'=>'Только владелец может менять роли'],403);if($other===$uid&&!$isSupreme)out(['ok'=>false,'error'=>'Нельзя изменить собственную роль'],403);$st=mysqli_prepare($link,"UPDATE community_server_members SET role=? WHERE server_id=? AND user_id=? AND role<>'owner'");mysqli_stmt_bind_param($st,'sii',$role,$sid,$other);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='create_invite'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$member=mysqli_query($link,"SELECT 1 FROM community_server_members WHERE server_id=$sid AND user_id=$uid");if(!$member||!mysqli_fetch_row($member))out(['ok'=>false,'error'=>'Нет доступа к серверу'],403);$code=bin2hex(random_bytes(16));$st=mysqli_prepare($link,"INSERT INTO community_server_invites(code,server_id,created_by,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 7 DAY))");mysqli_stmt_bind_param($st,'sii',$code,$sid,$uid);mysqli_stmt_execute($st);out(['ok'=>true,'code'=>$code,'url'=>'https://oliverkitchen.ru/invite.php?code='.$code]);}
if($action==='join_invite'&&$_SERVER['REQUEST_METHOD']==='POST'){$code=preg_replace('/[^a-f0-9]/i','',(string)($_POST['code']??''));$safe=mysqli_real_escape_string($link,$code);$r=mysqli_query($link,"SELECT server_id FROM community_server_invites WHERE code='$safe' AND (expires_at IS NULL OR expires_at>NOW()) LIMIT 1");$invite=$r?mysqli_fetch_assoc($r):null;if(!$invite)out(['ok'=>false,'error'=>'Ссылка приглашения недействительна'],404);$sid=(int)$invite['server_id'];mysqli_query($link,"INSERT IGNORE INTO community_server_members(server_id,user_id,role) VALUES($sid,$uid,'member')");mysqli_query($link,"UPDATE community_server_invites SET uses=uses+1 WHERE code='$safe'");out(['ok'=>true,'server_id'=>$sid]);}
if($action==='create_channel'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);if(!community_can($link,$sid,$uid,'admin'))out(['ok'=>false,'error'=>'Создавать каналы могут владелец и администраторы'],403);$name=trim((string)($_POST['name']??''));$type=($_POST['type']??'text')==='voice'?'voice':'text';$voiceMode='p2p';$topic=mb_substr(trim((string)($_POST['topic']??'')),0,180);if($name===''||mb_strlen($name)>60)out(['ok'=>false,'error'=>'Название: от 1 до 60 символов'],422);$slug=channel_slug($name).'-'.substr(bin2hex(random_bytes(3)),0,5);$st=mysqli_prepare($link,"INSERT INTO community_channels(server_id,slug,name,topic,type,voice_mode,owner_id,position) VALUES(?,?,?,?,?,?,?,100)");mysqli_stmt_bind_param($st,'isssssi',$sid,$slug,$name,$topic,$type,$voiceMode,$uid);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='update_channel'&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id']??0);$name=mb_substr(trim((string)($_POST['name']??'')),0,60);$topic=mb_substr(trim((string)($_POST['topic']??'')),0,180);$r=mysqli_query($link,"SELECT server_id FROM community_channels WHERE id=$id");$c=$r?mysqli_fetch_assoc($r):null;if(!$c||!community_can($link,(int)$c['server_id'],$uid,'admin'))out(['ok'=>false,'error'=>'Изменять каналы могут владелец и администраторы'],403);if($name==='')out(['ok'=>false,'error'=>'Введите название'],422);$st=mysqli_prepare($link,"UPDATE community_channels SET name=?,topic=? WHERE id=?");mysqli_stmt_bind_param($st,'ssi',$name,$topic,$id);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='delete_channel'&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id']??0);$r=mysqli_query($link,"SELECT slug,owner_id,server_id FROM community_channels WHERE id=$id");$c=$r?mysqli_fetch_assoc($r):null;if(!$c||(int)$c['owner_id']===0||!community_can($link,(int)$c['server_id'],$uid,'admin'))out(['ok'=>false,'error'=>'Удалять каналы могут владелец и администраторы'],403);$slug=mysqli_real_escape_string($link,$c['slug']);$sid=(int)$c['server_id'];$assets=mysqli_query($link,"SELECT message FROM community_messages WHERE server_id=$sid AND channel='$slug'");while($assets&&$asset=mysqli_fetch_assoc($assets))delete_message_asset($asset['message']);mysqli_query($link,"DELETE FROM community_channels WHERE id=$id");mysqli_query($link,"DELETE FROM community_messages WHERE server_id=$sid AND channel='$slug'");out(['ok'=>true]);}
if($action==='send'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$ch=(string)($_POST['channel']??'');$safe=mysqli_real_escape_string($link,$ch);$r=mysqli_query($link,"SELECT 1 FROM community_channels c JOIN community_server_members m ON m.server_id=c.server_id AND m.user_id=$uid WHERE c.server_id=$sid AND c.slug='$safe' AND c.type='text'");$msg=trim((string)($_POST['message']??''));if(!$r||!mysqli_fetch_row($r)||$msg===''||mb_strlen($msg)>2000)out(['ok'=>false,'error'=>'Не удалось отправить'],422);try{$stored=chat_encrypt($msg);}catch(Throwable $e){out(['ok'=>false,'error'=>'Ошибка защиты сообщения'],500);}$st=mysqli_prepare($link,'INSERT INTO community_messages(server_id,channel,user_id,message) VALUES(?,?,?,?)');mysqli_stmt_bind_param($st,'isis',$sid,$ch,$uid,$stored);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='edit_message'&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id']??0);$msg=trim((string)($_POST['message']??''));if($msg===''||mb_strlen($msg)>2000)out(['ok'=>false,'error'=>'Сообщение не может быть пустым'],422);$r=mysqli_query($link,"SELECT user_id,message FROM community_messages WHERE id=$id");$row=$r?mysqli_fetch_assoc($r):null;$plain=$row?chat_decrypt($row['message']):'';if(!$row||(int)$row['user_id']!==$uid||str_starts_with($plain,'[['))out(['ok'=>false,'error'=>'Это сообщение нельзя редактировать'],403);$stored=chat_encrypt($msg);$st=mysqli_prepare($link,"UPDATE community_messages SET message=?,edited_at=NOW() WHERE id=? AND user_id=?");mysqli_stmt_bind_param($st,'sii',$stored,$id,$uid);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='delete_message'&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id']??0);$r=mysqli_query($link,"SELECT msg.user_id,msg.message,s.owner_id,member.role FROM community_messages msg JOIN community_servers s ON s.id=msg.server_id LEFT JOIN community_server_members member ON member.server_id=msg.server_id AND member.user_id=$uid WHERE msg.id=$id");$row=$r?mysqli_fetch_assoc($r):null;if(!$row||((int)$row['user_id']!==$uid&&(int)$row['owner_id']!==$uid&&!in_array($row['role']??'',['admin','moderator'],true)&&!admin_user($uid)))out(['ok'=>false,'error'=>'Недостаточно прав'],403);delete_message_asset($row['message']);mysqli_query($link,"DELETE FROM community_messages WHERE id=$id");out(['ok'=>true]);}
if($action==='clear_channel'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$ch=mysqli_real_escape_string($link,(string)($_POST['channel']??''));if(!community_can($link,$sid,$uid,'admin'))out(['ok'=>false,'error'=>'Очищать канал могут владелец и администраторы'],403);$before=trim((string)($_POST['before']??''));$dateSql=preg_match('/^\d{4}-\d{2}-\d{2}$/',$before)?" AND created_at<='$before 23:59:59'":'';$r=mysqli_query($link,"SELECT message FROM community_messages WHERE server_id=$sid AND channel='$ch'$dateSql");while($r&&$row=mysqli_fetch_assoc($r))delete_message_asset($row['message']);mysqli_query($link,"DELETE FROM community_messages WHERE server_id=$sid AND channel='$ch'$dateSql");out(['ok'=>true]);}
if($action==='mark_read'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$ch=(string)($_POST['channel']??'');$last=max(0,(int)($_POST['last_message_id']??0));$st=mysqli_prepare($link,"INSERT INTO community_message_reads(server_id,channel,user_id,last_message_id) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE read_at=IF(VALUES(last_message_id)>last_message_id,NOW(),read_at),last_message_id=GREATEST(last_message_id,VALUES(last_message_id))");mysqli_stmt_bind_param($st,'isii',$sid,$ch,$uid,$last);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='send_file'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$ch=(string)($_POST['channel']??'');$safe=mysqli_real_escape_string($link,$ch);$r=mysqli_query($link,"SELECT 1 FROM community_channels c JOIN community_server_members m ON m.server_id=c.server_id AND m.user_id=$uid WHERE c.server_id=$sid AND c.slug='$safe' AND c.type='text'");if(!$r||!mysqli_fetch_row($r))out(['ok'=>false,'error'=>'Нет доступа к каналу'],403);$file=save_attachment($_FILES['file']??null,$sid);if(!$file)out(['ok'=>false,'error'=>'Поддерживаются изображения, видео, аудио, PDF, ZIP и текстовые файлы до 25 МБ'],422);$stored=chat_encrypt('[[file:'.base64_encode(json_encode($file,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)).']]');$st=mysqli_prepare($link,'INSERT INTO community_messages(server_id,channel,user_id,message) VALUES(?,?,?,?)');mysqli_stmt_bind_param($st,'isis',$sid,$ch,$uid,$stored);mysqli_stmt_execute($st);out(['ok'=>true,'attachment'=>$file]);}
if($action==='upload_sticker'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$member=mysqli_query($link,"SELECT 1 FROM community_server_members WHERE server_id=$sid AND user_id=$uid");if(!$member||!mysqli_fetch_row($member))out(['ok'=>false,'error'=>'Нет доступа к серверу'],403);$name=mb_substr(trim((string)($_POST['name']??'Стикер')),0,60)?:'Стикер';$path=save_sticker($_FILES['sticker']??null,$sid);if(!$path)out(['ok'=>false,'error'=>'Выберите JPG, JPEG, PNG, WEBP или GIF до 8 МБ'],422);$st=mysqli_prepare($link,"INSERT INTO community_stickers(server_id,user_id,name,path) VALUES(?,?,?,?)");mysqli_stmt_bind_param($st,'iiss',$sid,$uid,$name,$path);mysqli_stmt_execute($st);out(['ok'=>true,'sticker'=>['id'=>(int)mysqli_insert_id($link),'name'=>$name,'path'=>$path]]);}
if($action==='send_sticker'&&$_SERVER['REQUEST_METHOD']==='POST'){$sid=(int)($_POST['server_id']??0);$stickerId=(int)($_POST['sticker_id']??0);$ch=(string)($_POST['channel']??'');$safe=mysqli_real_escape_string($link,$ch);$allowed=mysqli_query($link,"SELECT 1 FROM community_stickers s JOIN community_server_members m ON m.server_id=s.server_id AND m.user_id=$uid JOIN community_channels c ON c.server_id=s.server_id AND c.slug='$safe' AND c.type='text' WHERE s.id=$stickerId AND s.server_id=$sid");if(!$allowed||!mysqli_fetch_row($allowed))out(['ok'=>false,'error'=>'Стикер недоступен'],403);$stored=chat_encrypt('[[sticker:'.$stickerId.']]');$st=mysqli_prepare($link,'INSERT INTO community_messages(server_id,channel,user_id,message) VALUES(?,?,?,?)');mysqli_stmt_bind_param($st,'isis',$sid,$ch,$uid,$stored);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='delete_sticker'&&$_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['sticker_id']??0);$r=mysqli_query($link,"SELECT st.path,st.user_id,st.server_id,s.owner_id FROM community_stickers st JOIN community_servers s ON s.id=st.server_id WHERE st.id=$id");$row=$r?mysqli_fetch_assoc($r):null;if(!$row||((int)$row['user_id']!==$uid&&(int)$row['owner_id']!==$uid&&!admin_user($uid)))out(['ok'=>false,'error'=>'Недостаточно прав'],403);delete_uploaded_path($row['path']);$sid=(int)$row['server_id'];$messages=mysqli_query($link,"SELECT id,message FROM community_messages WHERE server_id=$sid");while($messages&&$message=mysqli_fetch_assoc($messages)){if(chat_decrypt($message['message'])==='[[sticker:'.$id.']]')mysqli_query($link,'DELETE FROM community_messages WHERE id='.(int)$message['id']);}mysqli_query($link,"DELETE FROM community_stickers WHERE id=$id");out(['ok'=>true]);}
if($action==='friend'&&$_SERVER['REQUEST_METHOD']==='POST'){$other=(int)($_POST['user_id']??0);$mode=$_POST['mode']??'add';if($other<=0||$other===$uid)out(['ok'=>false],422);if($mode==='add')mysqli_query($link,"INSERT INTO friends(user_id,friend_id,status) SELECT $uid,$other,0 WHERE NOT EXISTS(SELECT 1 FROM friends WHERE (user_id=$uid AND friend_id=$other) OR (user_id=$other AND friend_id=$uid))");elseif($mode==='accept')mysqli_query($link,"UPDATE friends SET status=1 WHERE user_id=$other AND friend_id=$uid AND status=0");elseif($mode==='cancel')mysqli_query($link,"DELETE FROM friends WHERE user_id=$uid AND friend_id=$other AND status=0");elseif($mode==='reject')mysqli_query($link,"DELETE FROM friends WHERE user_id=$other AND friend_id=$uid AND status=0");elseif($mode==='remove')mysqli_query($link,"DELETE FROM friends WHERE (user_id=$uid AND friend_id=$other) OR (user_id=$other AND friend_id=$uid)");out(['ok'=>true]);}
if($action==='voice_join'&&$_SERVER['REQUEST_METHOD']==='POST'){$cid=(int)($_POST['channel_id']??0);mysqli_begin_transaction($link);try{mysqli_query($link,"DELETE FROM community_voice_presence WHERE user_id=$uid");mysqli_query($link,"DELETE FROM community_voice_signals WHERE sender_id=$uid OR receiver_id=$uid");mysqli_query($link,"INSERT INTO community_voice_presence(channel_id,user_id) SELECT c.id,$uid FROM community_channels c JOIN community_server_members m ON m.server_id=c.server_id AND m.user_id=$uid WHERE c.id=$cid AND c.type='voice'");if(mysqli_affected_rows($link)!==1)throw new RuntimeException('Voice channel unavailable');mysqli_commit($link);out(['ok'=>true]);}catch(Throwable $e){mysqli_rollback($link);out(['ok'=>false,'error'=>'Голосовой канал недоступен'],422);}}
if($action==='voice_state'&&$_SERVER['REQUEST_METHOD']==='POST'){$cid=(int)($_POST['channel_id']??0);$muted=!empty($_POST['muted'])?1:0;$deafened=!empty($_POST['deafened'])?1:0;$speaking=!empty($_POST['speaking'])&&!$muted?1:0;$sharing=!empty($_POST['sharing'])?1:0;$camera=!empty($_POST['camera'])?1:0;$mode=mysqli_query($link,"SELECT voice_mode FROM community_channels WHERE id=$cid AND type='voice'");$channelMode=$mode?mysqli_fetch_assoc($mode):null;if(!$channelMode)out(['ok'=>false],404);$st=mysqli_prepare($link,"UPDATE community_voice_presence SET muted=?,deafened=?,speaking=?,sharing=?,camera=?,heartbeat_at=NOW() WHERE channel_id=? AND user_id=?");mysqli_stmt_bind_param($st,'iiiiiii',$muted,$deafened,$speaking,$sharing,$camera,$cid,$uid);mysqli_stmt_execute($st);$present=mysqli_query($link,"SELECT 1 FROM community_voice_presence WHERE channel_id=$cid AND user_id=$uid LIMIT 1");out(['ok'=>true,'connected'=>(bool)($present&&mysqli_fetch_row($present))]);}
if($action==='voice_leave'&&$_SERVER['REQUEST_METHOD']==='POST'){$cid=(int)($_POST['channel_id']??0);mysqli_query($link,"DELETE FROM community_voice_presence WHERE channel_id=$cid AND user_id=$uid");mysqli_query($link,"DELETE FROM community_voice_signals WHERE channel_id=$cid AND (sender_id=$uid OR receiver_id=$uid)");out(['ok'=>true]);}
if($action==='voice_leave_all'&&$_SERVER['REQUEST_METHOD']==='POST'){mysqli_query($link,"DELETE FROM community_voice_presence WHERE user_id=$uid");mysqli_query($link,"DELETE FROM community_voice_signals WHERE sender_id=$uid OR receiver_id=$uid");out(['ok'=>true]);}
if($action==='voice_signal'&&$_SERVER['REQUEST_METHOD']==='POST'){$cid=(int)($_POST['channel_id']??0);$to=(int)($_POST['to']??0);$payload=(string)($_POST['payload']??'');$allowed=mysqli_query($link,"SELECT 1 FROM community_channels c JOIN community_server_members sender ON sender.server_id=c.server_id AND sender.user_id=$uid JOIN community_server_members receiver ON receiver.server_id=c.server_id AND receiver.user_id=$to JOIN community_voice_presence p ON p.user_id=$to AND p.channel_id=c.id WHERE c.id=$cid AND c.type='voice' LIMIT 1");if($to<=0||!$allowed||!mysqli_fetch_row($allowed)||strlen($payload)>40000||!json_decode($payload,true))out(['ok'=>false],422);$st=mysqli_prepare($link,"INSERT INTO community_voice_signals(channel_id,sender_id,receiver_id,payload) VALUES(?,?,?,?)");mysqli_stmt_bind_param($st,'iiis',$cid,$uid,$to,$payload);mysqli_stmt_execute($st);out(['ok'=>true]);}
if($action==='voice_poll'){$cid=(int)($_GET['channel_id']??0);$after=max(0,(int)($_GET['after']??0));$allowed=mysqli_query($link,"SELECT 1 FROM community_channels c JOIN community_server_members m ON m.server_id=c.server_id AND m.user_id=$uid WHERE c.id=$cid AND c.type='voice'");if(!$allowed||!mysqli_fetch_row($allowed))out(['ok'=>false,'error'=>'P2P-канал недоступен'],403);mysqli_query($link,"UPDATE community_voice_presence SET heartbeat_at=NOW() WHERE channel_id=$cid AND user_id=$uid");$signals=[];$r=mysqli_query($link,"SELECT id,sender_id,payload FROM community_voice_signals WHERE channel_id=$cid AND receiver_id=$uid AND id>$after ORDER BY id LIMIT 100");while($r&&$x=mysqli_fetch_assoc($r))$signals[]=['id'=>(int)$x['id'],'from'=>(int)$x['sender_id'],'payload'=>json_decode($x['payload'],true)];$users=[];$r=mysqli_query($link,"SELECT u.id,u.name,u.avatar,p.muted,p.deafened,p.speaking,p.sharing,p.camera FROM community_voice_presence p JOIN user u ON u.id=p.user_id WHERE p.channel_id=$cid AND p.heartbeat_at>=DATE_SUB(NOW(),INTERVAL 25 SECOND) ORDER BY p.joined_at,u.id");while($r&&$v=mysqli_fetch_assoc($r))$users[]=['channel_id'=>$cid,'id'=>(int)$v['id'],'name'=>$v['name'],'avatar'=>$v['avatar'],'muted'=>(bool)$v['muted'],'deafened'=>(bool)$v['deafened'],'speaking'=>(bool)$v['speaking'],'sharing'=>(bool)$v['sharing'],'camera'=>(bool)$v['camera']];out(['ok'=>true,'signals'=>$signals,'users'=>$users]);}
$servers=[];$sr=mysqli_query($link,"SELECT s.*,m.role FROM community_servers s JOIN community_server_members m ON m.server_id=s.id WHERE m.user_id=$uid ORDER BY s.id");while($sr&&$s=mysqli_fetch_assoc($sr)){$s['id']=(int)$s['id'];$s['owner_id']=(int)$s['owner_id'];$servers[]=$s;}$serverId=(int)($_GET['server_id']??0);if(!$serverId&&$servers)$serverId=$servers[0]['id'];$activeServer=null;foreach($servers as $s)if($s['id']===$serverId)$activeServer=$s;if(!$activeServer)$serverId=0;
$channel=(string)($_GET['channel']??'');$since=max(0,(int)($_GET['since']??0));$channels=[];$r=mysqli_query($link,"SELECT id,slug,name,topic,type,voice_mode,owner_id,position FROM community_channels WHERE server_id=$serverId ORDER BY type='voice',position,id");while($r&&$c=mysqli_fetch_assoc($r)){$c['id']=(int)$c['id'];$c['owner_id']=(int)$c['owner_id'];$c['voice_mode']='p2p'; // Legacy rows use P2P without erasing the stored fallback mode.
$c['can_edit']=$c['owner_id']>0&&($isSupreme||($activeServer&&in_array($activeServer['role']??'',['owner','admin'],true)));$channels[]=$c;}
$stickerMap=[];$stickers=[];$r=mysqli_query($link,"SELECT id,name,path,user_id FROM community_stickers WHERE server_id=$serverId ORDER BY id DESC LIMIT 100");while($r&&$s=mysqli_fetch_assoc($r)){$s['id']=(int)$s['id'];$s['user_id']=(int)$s['user_id'];$stickers[]=$s;$stickerMap[$s['id']]=$s;}
$messages=[];$baseMessageSql="SELECT m.id,m.message,m.created_at,m.edited_at,u.id user_id,u.name,u.avatar,(SELECT COUNT(*) FROM community_message_reads rd WHERE rd.server_id=m.server_id AND rd.channel=m.channel AND rd.user_id<>m.user_id AND rd.last_message_id>=m.id) read_by FROM community_messages m JOIN user u ON u.id=m.user_id WHERE m.server_id=? AND m.channel=?";if($since>0){$st=mysqli_prepare($link,$baseMessageSql." AND m.id>? ORDER BY m.id LIMIT 100");mysqli_stmt_bind_param($st,'isi',$serverId,$channel,$since);}else{$st=mysqli_prepare($link,"SELECT * FROM (".$baseMessageSql." ORDER BY m.id DESC LIMIT 100) recent ORDER BY id");mysqli_stmt_bind_param($st,'is',$serverId,$channel);}mysqli_stmt_execute($st);$r=mysqli_stmt_get_result($st);while($r&&$x=mysqli_fetch_assoc($r)){$x['id']=(int)$x['id'];$x['user_id']=(int)$x['user_id'];$x['read_by']=(int)$x['read_by'];$x['message']=chat_decrypt($x['message']);if(preg_match('/^\[\[sticker:(\d+)\]\]$/',$x['message'],$match)&&isset($stickerMap[(int)$match[1]])){$x['sticker']=$stickerMap[(int)$match[1]];$x['message']='';}elseif(preg_match('/^\[\[file:([A-Za-z0-9+\/=]+)\]\]$/',$x['message'],$match)){$file=json_decode(base64_decode($match[1]),true);if(is_array($file)&&!empty($file['path'])){$x['attachment']=$file;$x['message']='';}}$messages[]=$x;}
$onlineSql=desktop_online_expression('u');
$people=[];$r=mysqli_query($link,"SELECT u.id,u.name,u.avatar,COALESCE(pa.about,'') about,$onlineSql online,f.status,f.user_id request_sender FROM user u LEFT JOIN desktop_profile_about pa ON pa.user_id=u.id JOIN friends f ON ((f.user_id=$uid AND f.friend_id=u.id) OR (f.friend_id=$uid AND f.user_id=u.id)) WHERE u.id<>$uid ORDER BY f.status DESC,online DESC,u.name");while($r&&$p=mysqli_fetch_assoc($r)){$people[]=['id'=>(int)$p['id'],'name'=>$p['name'],'avatar'=>$p['avatar'],'about'=>$p['about'],'online'=>(bool)$p['online'],'friend_status'=>(int)$p['status'],'sent_by_me'=>(int)$p['request_sender']===$uid];}
$q=trim((string)($_GET['q']??''));$search=[];if($q!==''){$like='%'.mysqli_real_escape_string($link,$q).'%';$r=mysqli_query($link,"SELECT u.id,u.name,u.avatar,COALESCE(pa.about,'') about,f.status,f.user_id request_sender FROM user u LEFT JOIN desktop_profile_about pa ON pa.user_id=u.id LEFT JOIN friends f ON ((f.user_id=$uid AND f.friend_id=u.id) OR(f.friend_id=$uid AND f.user_id=u.id)) WHERE u.id<>$uid AND (u.name LIKE '$like' OR u.id='".(int)$q."') ORDER BY u.name LIMIT 20");while($r&&$p=mysqli_fetch_assoc($r))$search[]=['id'=>(int)$p['id'],'name'=>$p['name'],'avatar'=>$p['avatar'],'about'=>$p['about'],'friend_status'=>$p['status']===null?-1:(int)$p['status'],'sent_by_me'=>(int)($p['request_sender']??0)===$uid];}
$voice=[];$r=mysqli_query($link,"SELECT p.channel_id,u.id,u.name,u.avatar,p.muted,p.deafened,p.speaking,p.sharing,p.camera FROM community_voice_presence p JOIN community_channels vc ON vc.id=p.channel_id JOIN user u ON u.id=p.user_id WHERE p.heartbeat_at>=DATE_SUB(NOW(),INTERVAL 25 SECOND) AND EXISTS(SELECT 1 FROM community_server_members viewer WHERE viewer.server_id=vc.server_id AND viewer.user_id=$uid) AND NOT EXISTS(SELECT 1 FROM community_voice_presence newer WHERE newer.user_id=p.user_id AND (newer.heartbeat_at>p.heartbeat_at OR (newer.heartbeat_at=p.heartbeat_at AND newer.channel_id>p.channel_id))) ORDER BY p.channel_id,p.joined_at,u.id");while($r&&$v=mysqli_fetch_assoc($r))$voice[]=['channel_id'=>(int)$v['channel_id'],'id'=>(int)$v['id'],'name'=>$v['name'],'avatar'=>$v['avatar'],'muted'=>(bool)$v['muted'],'deafened'=>(bool)$v['deafened'],'speaking'=>(bool)$v['speaking'],'sharing'=>(bool)$v['sharing'],'camera'=>(bool)$v['camera']];
$serverMembers=[];$r=mysqli_query($link,"SELECT u.id,u.name,u.avatar,COALESCE(pa.about,'') about,u.global_role,m.role,$onlineSql online FROM community_server_members m JOIN user u ON u.id=m.user_id LEFT JOIN desktop_profile_about pa ON pa.user_id=u.id WHERE m.server_id=$serverId ORDER BY u.global_role='superadmin' DESC,m.role='owner' DESC,online DESC,u.name");while($r&&$m=mysqli_fetch_assoc($r))$serverMembers[]=['id'=>(int)$m['id'],'name'=>$m['name'],'avatar'=>$m['avatar'],'about'=>$m['about'],'role'=>$m['role'],'global_role'=>$m['global_role'],'online'=>(bool)$m['online']];
$safeChannel=mysqli_real_escape_string($link,$channel);$messageSync=['count'=>0,'max_id'=>0,'changed'=>'','read_changed'=>''];$syncResult=mysqli_query($link,"SELECT COUNT(*) count,COALESCE(MAX(id),0) max_id,COALESCE(MAX(COALESCE(edited_at,created_at)),'') changed FROM community_messages WHERE server_id=$serverId AND channel='$safeChannel'");if($syncResult&&$syncRow=mysqli_fetch_assoc($syncResult))$messageSync=['count'=>(int)$syncRow['count'],'max_id'=>(int)$syncRow['max_id'],'changed'=>$syncRow['changed'],'read_changed'=>''];$readSync=mysqli_query($link,"SELECT COALESCE(MAX(read_at),'') changed FROM community_message_reads WHERE server_id=$serverId AND channel='$safeChannel'");if($readSync&&$readRow=mysqli_fetch_assoc($readSync))$messageSync['read_changed']=$readRow['changed'];
out(['ok'=>true,'me'=>['id'=>$uid,'admin'=>$isSupreme,'global_role'=>$isSupreme?'superadmin':'user','title'=>$isSupreme?'Самый главный':null],'servers'=>$servers,'server'=>$activeServer,'channels'=>$channels,'messages'=>$messages,'message_sync'=>$messageSync,'people'=>$people,'search'=>$search,'voice'=>$voice,'stickers'=>$stickers,'server_members'=>$serverMembers]);
