<?php
require_once __DIR__.'/../bd/database.php';require_once __DIR__.'/../bd/desktop_session.php';
desktop_cors();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');mysqli_set_charset($link,'utf8mb4');
function desktop_out(array $data,int $status=200):void{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function desktop_input():array{$raw=file_get_contents('php://input');$json=json_decode($raw,true);return is_array($json)?$json:$_POST;}
function desktop_profile_about_prepare(mysqli $db):void{$db->query("CREATE TABLE IF NOT EXISTS desktop_profile_about(user_id INT NOT NULL PRIMARY KEY,about VARCHAR(190) NOT NULL DEFAULT '',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_profile_about_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
function desktop_user(mysqli $db,int $id):array{desktop_profile_about_prepare($db);$st=$db->prepare("SELECT u.id,u.name,u.login,u.avatar,COALESCE(p.about,'') about FROM user u LEFT JOIN desktop_profile_about p ON p.user_id=u.id WHERE u.id=? LIMIT 1");$st->bind_param('i',$id);$st->execute();$u=$st->get_result()->fetch_assoc();$st->close();return $u?:[];}
$input=desktop_input();$action=(string)($input['action']??$_GET['action']??'me');desktop_session_prepare($link);
if($action==='oauth_exchange'){$code=(string)($input['code']??'');$uid=desktop_oauth_code_consume($link,$code);if($uid<=0)desktop_out(['ok'=>false,'error'=>'Ссылка входа недействительна или уже использована'],401);desktop_out(['ok'=>true,'token'=>desktop_session_create($link,$uid),'user'=>desktop_user($link,$uid)]);}
if($action==='login'){$login=trim((string)($input['login']??''));$password=(string)($input['password']??'');if($login===''||$password==='')desktop_out(['ok'=>false,'error'=>'Введите логин и пароль'],422);$st=$link->prepare('SELECT id,password FROM user WHERE login=? LIMIT 1');$st->bind_param('s',$login);$st->execute();$row=$st->get_result()->fetch_assoc();$st->close();$stored=(string)($row['password']??'');$isHash=password_get_info($stored)['algo']!==null&&password_get_info($stored)['algo']!==0;$valid=$row&&($isHash?password_verify($password,$stored):hash_equals($stored,$password));if(!$valid)desktop_out(['ok'=>false,'error'=>'Неверный логин или пароль'],401);$uid=(int)$row['id'];if(!$isHash){$newHash=password_hash($password,PASSWORD_DEFAULT);$up=$link->prepare('UPDATE user SET password=? WHERE id=?');$up->bind_param('si',$newHash,$uid);$up->execute();$up->close();}desktop_out(['ok'=>true,'token'=>desktop_session_create($link,$uid),'user'=>desktop_user($link,$uid)]);}
if($action==='register'){$login=mb_strtolower(trim((string)($input['login']??'')));$name=trim((string)($input['name']??''));$password=(string)($input['password']??'');if(!preg_match('/^[^\s@]+@[^\s@]+\.[^\s@]+$/',$login))desktop_out(['ok'=>false,'error'=>'Введите корректную почту'],422);if(mb_strlen($name)<2||mb_strlen($name)>40)desktop_out(['ok'=>false,'error'=>'Имя должно содержать от 2 до 40 символов'],422);if(strlen($password)<8)desktop_out(['ok'=>false,'error'=>'Пароль должен содержать минимум 8 символов'],422);$check=$link->prepare('SELECT id FROM user WHERE login=? LIMIT 1');$check->bind_param('s',$login);$check->execute();$exists=$check->get_result()->fetch_assoc();$check->close();if($exists)desktop_out(['ok'=>false,'error'=>'Аккаунт с такой почтой уже существует'],409);$hash=password_hash($password,PASSWORD_DEFAULT);$avatar='';$st=$link->prepare('INSERT INTO user(login,password,name,avatar) VALUES(?,?,?,?)');$st->bind_param('ssss',$login,$hash,$name,$avatar);if(!$st->execute())desktop_out(['ok'=>false,'error'=>'Не удалось создать аккаунт'],500);$uid=(int)$st->insert_id;$st->close();desktop_out(['ok'=>true,'token'=>desktop_session_create($link,$uid),'user'=>desktop_user($link,$uid)],201);}
$uid=desktop_session_user($link);if($uid<=0)desktop_out(['ok'=>false,'error'=>'Сессия истекла'],401);
if($action==='update_profile'){$name=trim((string)($input['name']??''));if(mb_strlen($name)<2||mb_strlen($name)>40)desktop_out(['ok'=>false,'error'=>'Имя должно содержать от 2 до 40 символов'],422);$st=$link->prepare('UPDATE user SET name=? WHERE id=?');$st->bind_param('si',$name,$uid);$st->execute();$st->close();if(array_key_exists('about',$input)){desktop_profile_about_prepare($link);$about=trim((string)$input['about']);$about=mb_substr($about,0,190);$st=$link->prepare('INSERT INTO desktop_profile_about(user_id,about) VALUES(?,?) ON DUPLICATE KEY UPDATE about=VALUES(about),updated_at=CURRENT_TIMESTAMP');$st->bind_param('is',$uid,$about);$st->execute();$st->close();}desktop_out(['ok'=>true,'user'=>desktop_user($link,$uid)]);}
if($action==='upload_avatar'){$file=$_FILES['avatar']??null;if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>5*1024*1024)desktop_out(['ok'=>false,'error'=>'Выберите изображение до 5 МБ'],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'][$mime]??null;if(!$ext||!@getimagesize($file['tmp_name']))desktop_out(['ok'=>false,'error'=>'Поддерживаются JPG, PNG, WEBP и GIF'],422);$dir=dirname(__DIR__).'/uploads/avatars';if(!is_dir($dir)&&!@mkdir($dir,0775,true))desktop_out(['ok'=>false,'error'=>'Не удалось подготовить хранилище'],500);$name='desktop-'.$uid.'-'.bin2hex(random_bytes(8)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))desktop_out(['ok'=>false,'error'=>'Не удалось сохранить аватар'],500);$path='/uploads/avatars/'.$name;$st=$link->prepare('UPDATE user SET avatar=? WHERE id=?');$st->bind_param('si',$path,$uid);$st->execute();$st->close();desktop_out(['ok'=>true,'user'=>desktop_user($link,$uid)]);}
if($action==='logout'){$token=desktop_bearer_token();$hash=hash('sha256',$token);$st=$link->prepare('DELETE FROM desktop_sessions WHERE token_hash=?');$st->bind_param('s',$hash);$st->execute();$st->close();desktop_out(['ok'=>true]);}
desktop_out(['ok'=>true,'user'=>desktop_user($link,$uid)]);
